from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]


class GpuUnavailableError(RuntimeError):
    pass


@dataclass
class RunConfig:
    python_bin: str
    output_root: Path
    dataset_cache_dir: Path
    specs: list[str]
    decoding_modes: list[str]
    alphas: list[float]
    seed: int
    num_episodes: int
    max_steps: int
    epochs: int
    batch_size: int
    block_size: int
    n_layer: int
    n_head: int
    n_embd: int
    eval_num_episodes: int
    eval_max_steps: int
    target_shift: str
    download_if_missing: bool
    download_retries: int
    download_sleep_sec: float
    continue_on_error: bool
    dry_run: bool
    parallel_workers: int
    require_gpu: bool
    gpu_check_interval_sec: float
    gpu_worker_map: list[int] | None


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run full TT+logic DSRL matrix (dataset x spec x decode x alpha).")
    p.add_argument(
        "--catalog_path",
        type=str,
        default="artifacts/dsrl_catalog/dsrl_catalog.json",
        help="Path to DSRL catalog JSON generated by scripts/dsrl_catalog.py.",
    )
    p.add_argument(
        "--output_root",
        type=str,
        default=None,
        help="Output root directory. Default: runs/dsrl/tt_dsrl_matrix_<UTC timestamp>/",
    )
    p.add_argument(
        "--dataset_cache_dir",
        type=str,
        default="artifacts/dsrl_datasets",
        help="Directory for dataset HDF5 cache files (<dataset_key>.hdf5).",
    )
    p.add_argument("--dataset_keys", nargs="*", default=None, help="Optional subset of dataset keys to run.")
    p.add_argument("--max_datasets", type=int, default=None, help="Optional cap on number of datasets after filtering.")
    p.add_argument(
        "--specs",
        nargs="+",
        default=["avoid_unsafe", "reach_goal", "reach_goal_while_avoid_unsafe"],
        help="Specs to run for each dataset.",
    )
    p.add_argument(
        "--decoding_modes",
        nargs="+",
        default=["greedy", "beam", "constrained_beam"],
        choices=["greedy", "beam", "constrained_beam"],
        help="Decoding modes to run for each spec.",
    )
    p.add_argument(
        "--alphas",
        nargs="+",
        type=float,
        default=[0.0, 0.01, 0.05, 0.1, 0.2, 0.4],
        help="Logic alpha sweep values.",
    )
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--num_episodes", type=int, default=5000)
    p.add_argument("--max_steps", type=int, default=200)
    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--batch_size", type=int, default=64)
    p.add_argument("--block_size", type=int, default=128)
    p.add_argument("--n_layer", type=int, default=4)
    p.add_argument("--n_head", type=int, default=4)
    p.add_argument("--n_embd", type=int, default=128)
    p.add_argument("--eval_num_episodes", type=int, default=256)
    p.add_argument("--eval_max_steps", type=int, default=200)
    p.add_argument("--target_shift", type=str, default="token", choices=["token", "transition"])
    p.add_argument("--python_bin", type=str, default=sys.executable, help="Python executable for subprocess calls.")
    p.add_argument("--download_retries", type=int, default=6)
    p.add_argument("--download_sleep_sec", type=float, default=5.0)
    p.add_argument(
        "--no_download_if_missing",
        action="store_true",
        help="Do not download dataset files that are missing in cache.",
    )
    p.add_argument("--continue_on_error", action="store_true", help="Continue matrix even when one run fails.")
    p.add_argument("--dry_run", action="store_true", help="Print commands only.")
    p.add_argument("--smoke", action="store_true", help="Small local smoke run.")
    p.add_argument("--parallel_workers", type=int, default=1, help="Number of parallel dataset workers.")
    p.add_argument(
        "--gpu_worker_map",
        type=str,
        default=None,
        help="Comma-separated GPU ids for workers, e.g. '0,0,1,1'. Length must equal --parallel_workers.",
    )
    p.add_argument(
        "--require_gpu",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Require CUDA availability before starting each dataset and while each run command executes.",
    )
    p.add_argument(
        "--gpu_check_interval_sec",
        type=float,
        default=10.0,
        help="Polling interval while subprocess runs (seconds) for GPU health checks.",
    )
    return p.parse_args()


def _apply_smoke(args: argparse.Namespace) -> None:
    if not args.smoke:
        return
    args.max_datasets = 1 if args.max_datasets is None else min(args.max_datasets, 1)
    args.specs = args.specs[:1]
    args.decoding_modes = args.decoding_modes[:1]
    args.alphas = args.alphas[:2]
    args.num_episodes = min(args.num_episodes, 200)
    args.max_steps = min(args.max_steps, 60)
    args.epochs = min(args.epochs, 1)
    args.batch_size = min(args.batch_size, 32)
    args.block_size = min(args.block_size, 32)
    args.n_layer = min(args.n_layer, 2)
    args.n_head = min(args.n_head, 2)
    args.n_embd = min(args.n_embd, 64)
    args.eval_num_episodes = min(args.eval_num_episodes, 32)
    args.eval_max_steps = min(args.eval_max_steps, 60)


def _utc_stamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S", time.gmtime())


def _decode_args(mode: str) -> list[str]:
    if mode == "greedy":
        return ["--decoding_mode", "greedy"]
    if mode == "beam":
        return ["--decoding_mode", "beam", "--beam_width", "4", "--plan_horizon", "4"]
    if mode == "constrained_beam":
        return [
            "--decoding_mode",
            "constrained_beam",
            "--beam_width",
            "4",
            "--plan_horizon",
            "4",
            "--sat_rerank_weight",
            "2.0",
            "--hard_prune_reject_sink",
        ]
    raise ValueError(f"Unknown decoding mode: {mode}")


def _download_with_retry(url: str, dst: Path, retries: int, sleep_sec: float) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        return
    last_err = None
    for i in range(max(1, retries)):
        try:
            print(f"[download] {url} -> {dst} (attempt {i + 1}/{retries})", flush=True)
            urllib.request.urlretrieve(url, str(dst))
            return
        except Exception as exc:  # pragma: no cover - network variability
            last_err = exc
            time.sleep(float(sleep_sec))
    raise RuntimeError(f"Failed to download {url}: {last_err}")


def _env_for_gpu(gpu_id: int | None) -> dict[str, str]:
    env = os.environ.copy()
    if gpu_id is not None:
        env["CUDA_VISIBLE_DEVICES"] = str(gpu_id)
    return env


def _gpu_visible(gpu_id: int) -> bool:
    if shutil.which("nvidia-smi") is None:
        return False
    proc = subprocess.run(
        ["nvidia-smi", "-i", str(gpu_id), "--query-gpu=name", "--format=csv,noheader"],
        capture_output=True,
        text=True,
        check=False,
    )
    return proc.returncode == 0


def _torch_cuda_available(python_bin: str, gpu_id: int) -> bool:
    env = _env_for_gpu(gpu_id)
    proc = subprocess.run(
        [python_bin, "-c", "import torch,sys; sys.exit(0 if torch.cuda.is_available() and torch.cuda.device_count() > 0 else 1)"],
        cwd=REPO_ROOT,
        env=env,
        check=False,
    )
    return proc.returncode == 0


def _assert_gpu_or_raise(cfg: RunConfig, gpu_id: int, context: str) -> None:
    if not cfg.require_gpu:
        return
    if not _gpu_visible(gpu_id):
        raise GpuUnavailableError(f"[{context}] GPU {gpu_id} unavailable via nvidia-smi.")
    if not _torch_cuda_available(cfg.python_bin, gpu_id):
        raise GpuUnavailableError(f"[{context}] GPU {gpu_id} unavailable via torch.cuda.")


def _run(
    cmd: list[str],
    *,
    cfg: RunConfig,
    gpu_id: int | None,
    stop_event: threading.Event,
) -> None:
    print("[run]", " ".join(cmd), flush=True)
    if cfg.dry_run:
        return

    env = _env_for_gpu(gpu_id)
    if gpu_id is not None:
        _assert_gpu_or_raise(cfg, gpu_id, context="pre-run")

    proc = subprocess.Popen(cmd, cwd=REPO_ROOT, env=env)
    try:
        while True:
            if stop_event.is_set():
                proc.terminate()
                try:
                    proc.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    proc.kill()
                raise RuntimeError("Stop requested due to failure in another worker.")

            code = proc.poll()
            if code is not None:
                if code != 0:
                    raise subprocess.CalledProcessError(code, cmd)
                return

            if gpu_id is not None and cfg.require_gpu:
                _assert_gpu_or_raise(cfg, gpu_id, context="mid-run")
            time.sleep(max(1.0, float(cfg.gpu_check_interval_sec)))
    except Exception:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        raise


def _read_metrics_rows(csv_path: Path, mode: str) -> list[dict]:
    rows: list[dict] = []
    if not csv_path.exists():
        return rows
    with csv_path.open(newline="") as f:
        for row in csv.DictReader(f):
            base = row.get("baseline", "")
            if not base.startswith("logic_alpha"):
                continue
            try:
                alpha = float(base.replace("logic_alpha", ""))
            except Exception:
                continue
            out = {
                "baseline": base,
                "alpha": alpha,
                "decoding_mode": mode,
            }
            for k in [
                "return_mean",
                "return_std",
                "violation_rate",
                "satisfaction_rate",
                "runtime_sec",
                "goal_rate",
                "hazard_hit_rate",
                "violation_rate_step",
                "violation_rate_episode",
                "seed",
                "spec",
                "env",
            ]:
                val = row.get(k)
                if val in (None, "", "None"):
                    out[k] = None
                else:
                    try:
                        out[k] = float(val)
                    except Exception:
                        out[k] = val
            rows.append(out)
    return rows


def _save_spec_aggregate(spec_dir: Path, decoding_modes: list[str]) -> None:
    rows: list[dict] = []
    for mode in decoding_modes:
        csv_path = spec_dir / mode / "baseline_metrics.csv"
        rows.extend(_read_metrics_rows(csv_path, mode=mode))
    if not rows:
        return

    rows = sorted(rows, key=lambda r: (float(r["alpha"]), str(r["decoding_mode"])))
    agg_dir = spec_dir / "aggregate"
    plot_dir = spec_dir / "plots"
    agg_dir.mkdir(parents=True, exist_ok=True)
    plot_dir.mkdir(parents=True, exist_ok=True)

    with (agg_dir / "alpha_decode_metrics.json").open("w") as f:
        json.dump(rows, f, indent=2)
    with (agg_dir / "alpha_decode_metrics.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    try:
        import matplotlib.pyplot as plt
    except Exception:
        return

    modes = sorted({str(r["decoding_mode"]) for r in rows})
    alphas = sorted({float(r["alpha"]) for r in rows})

    # metrics_bar.png
    x = np.arange(len(alphas))
    width = 0.25
    plt.figure(figsize=(10, 4))
    for i, mode in enumerate(modes):
        vals = []
        for alpha in alphas:
            picks = [r for r in rows if r["decoding_mode"] == mode and float(r["alpha"]) == float(alpha)]
            sat = [float(r["satisfaction_rate"]) for r in picks if r.get("satisfaction_rate") is not None]
            vals.append(float(np.mean(sat)) if sat else np.nan)
        offset = (i - (len(modes) - 1) / 2.0) * width
        plt.bar(x + offset, np.nan_to_num(vals, nan=0.0), width=width, label=mode)
    plt.xticks(x, [str(a) for a in alphas])
    plt.xlabel("alpha")
    plt.ylabel("satisfaction_rate")
    plt.title("Satisfaction by Alpha and Decoding Mode")
    plt.legend()
    plt.tight_layout()
    plt.savefig(plot_dir / "metrics_bar.png")
    plt.close()

    # satisfaction_trend.png
    plt.figure(figsize=(8, 4))
    for mode in modes:
        ys = []
        for alpha in alphas:
            picks = [r for r in rows if r["decoding_mode"] == mode and float(r["alpha"]) == float(alpha)]
            sat = [float(r["satisfaction_rate"]) for r in picks if r.get("satisfaction_rate") is not None]
            ys.append(float(np.mean(sat)) if sat else np.nan)
        plt.plot(alphas, np.nan_to_num(ys, nan=0.0), marker="o", label=mode)
    plt.ylim(-0.05, 1.05)
    plt.xlabel("alpha")
    plt.ylabel("satisfaction_rate")
    plt.title("Satisfaction Trend")
    plt.legend()
    plt.tight_layout()
    plt.savefig(plot_dir / "satisfaction_trend.png")
    plt.close()

    # return_vs_satisfaction.png
    plt.figure(figsize=(6, 5))
    for mode in modes:
        picks = [
            r
            for r in rows
            if r["decoding_mode"] == mode
            and r.get("return_mean") is not None
            and r.get("satisfaction_rate") is not None
        ]
        if not picks:
            continue
        xs = [float(r["return_mean"]) for r in picks]
        ys = [float(r["satisfaction_rate"]) for r in picks]
        plt.scatter(xs, ys, label=mode)
        for r in picks:
            plt.annotate(f"a={r['alpha']}", (float(r["return_mean"]), float(r["satisfaction_rate"])), fontsize=7)
    plt.xlabel("return_mean")
    plt.ylabel("satisfaction_rate")
    plt.title("Return vs Satisfaction")
    plt.legend()
    plt.tight_layout()
    plt.savefig(plot_dir / "return_vs_satisfaction.png")
    plt.close()


def _process_row(
    row: dict[str, Any],
    *,
    cfg: RunConfig,
    gpu_id: int | None,
    stop_event: threading.Event,
    progress_counter: list[int],
    progress_lock: threading.Lock,
    total_jobs: int,
) -> list[dict[str, Any]]:
    failures: list[dict[str, Any]] = []

    key = str(row["dataset_key"])
    family = str(row.get("family", "unknown_family"))
    diff = str(row.get("difficulty", "unspecified"))
    url = row.get("dataset_url")
    ds_path = cfg.dataset_cache_dir / f"{key}.hdf5"

    if stop_event.is_set():
        return failures

    # Before starting each dataset, verify GPU if required.
    if gpu_id is not None:
        _assert_gpu_or_raise(cfg, gpu_id, context=f"dataset-start:{key}")

    try:
        if not ds_path.exists():
            if not cfg.download_if_missing:
                raise FileNotFoundError(f"Dataset not found in cache and download disabled: {ds_path}")
            if not url:
                raise ValueError(f"Missing dataset_url in catalog for key={key}")
            _download_with_retry(
                str(url),
                ds_path,
                retries=cfg.download_retries,
                sleep_sec=cfg.download_sleep_sec,
            )
    except Exception as exc:
        failures.append({"dataset_key": key, "stage": "dataset_prepare", "error": str(exc)})
        if not cfg.continue_on_error:
            raise
        return failures

    for spec in cfg.specs:
        spec_dir = cfg.output_root / family / diff / key / spec
        for mode in cfg.decoding_modes:
            if stop_event.is_set():
                return failures
            mode_dir = spec_dir / mode
            mode_dir.mkdir(parents=True, exist_ok=True)
            with progress_lock:
                progress_counter[0] += 1
                cur = progress_counter[0]
            print(
                f"[job {cur}/{total_jobs}] worker_gpu={gpu_id} dataset={key} spec={spec} mode={mode}",
                flush=True,
            )

            if (mode_dir / "baseline_metrics.csv").exists():
                print(f"[skip] Existing output: {mode_dir / 'baseline_metrics.csv'}", flush=True)
                continue

            cmd = [
                cfg.python_bin,
                "scripts/run_baselines.py",
                "--env",
                "dsrl",
                "--spec",
                spec,
                "--seed",
                str(cfg.seed),
                "--target_shift",
                cfg.target_shift,
                "--dsrl_dataset_path",
                str(ds_path),
                "--num_episodes",
                str(cfg.num_episodes),
                "--max_steps",
                str(cfg.max_steps),
                "--epochs",
                str(cfg.epochs),
                "--batch_size",
                str(cfg.batch_size),
                "--block_size",
                str(cfg.block_size),
                "--n_layer",
                str(cfg.n_layer),
                "--n_head",
                str(cfg.n_head),
                "--n_embd",
                str(cfg.n_embd),
                "--evaluate",
                "--eval_num_episodes",
                str(cfg.eval_num_episodes),
                "--eval_max_steps",
                str(cfg.eval_max_steps),
                "--baselines",
                "logic",
                "--alphas",
            ] + [str(a) for a in cfg.alphas] + _decode_args(mode) + ["--base_run_dir", str(mode_dir)]

            try:
                _run(cmd, cfg=cfg, gpu_id=gpu_id, stop_event=stop_event)
            except GpuUnavailableError:
                stop_event.set()
                raise
            except Exception as exc:
                failures.append(
                    {
                        "dataset_key": key,
                        "family": family,
                        "difficulty": diff,
                        "spec": spec,
                        "mode": mode,
                        "stage": "run_baselines",
                        "error": str(exc),
                    }
                )
                if not cfg.continue_on_error:
                    raise
                continue

        _save_spec_aggregate(spec_dir, cfg.decoding_modes)

    return failures


def _worker_loop(
    worker_idx: int,
    rows: list[dict[str, Any]],
    *,
    cfg: RunConfig,
    gpu_id: int | None,
    stop_event: threading.Event,
    progress_counter: list[int],
    progress_lock: threading.Lock,
    total_jobs: int,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for row in rows:
        if stop_event.is_set():
            break
        try:
            out.extend(
                _process_row(
                    row,
                    cfg=cfg,
                    gpu_id=gpu_id,
                    stop_event=stop_event,
                    progress_counter=progress_counter,
                    progress_lock=progress_lock,
                    total_jobs=total_jobs,
                )
            )
        except GpuUnavailableError as exc:
            stop_event.set()
            raise GpuUnavailableError(f"worker={worker_idx} gpu={gpu_id}: {exc}") from exc
    return out


def _resolve_gpu_worker_map(args: argparse.Namespace) -> list[int] | None:
    if args.gpu_worker_map:
        parsed = [int(x.strip()) for x in str(args.gpu_worker_map).split(",") if x.strip() != ""]
        if len(parsed) != int(args.parallel_workers):
            raise ValueError(
                f"--gpu_worker_map length ({len(parsed)}) must equal --parallel_workers ({args.parallel_workers})."
            )
        return parsed
    return None


def main() -> None:
    args = _parse_args()
    _apply_smoke(args)

    out_root = Path(args.output_root) if args.output_root else Path(f"runs/dsrl/tt_dsrl_matrix_{_utc_stamp()}")
    out_root.mkdir(parents=True, exist_ok=True)

    cfg = RunConfig(
        python_bin=str(args.python_bin),
        output_root=out_root,
        dataset_cache_dir=Path(args.dataset_cache_dir),
        specs=list(args.specs),
        decoding_modes=list(args.decoding_modes),
        alphas=[float(a) for a in args.alphas],
        seed=int(args.seed),
        num_episodes=int(args.num_episodes),
        max_steps=int(args.max_steps),
        epochs=int(args.epochs),
        batch_size=int(args.batch_size),
        block_size=int(args.block_size),
        n_layer=int(args.n_layer),
        n_head=int(args.n_head),
        n_embd=int(args.n_embd),
        eval_num_episodes=int(args.eval_num_episodes),
        eval_max_steps=int(args.eval_max_steps),
        target_shift=str(args.target_shift),
        download_if_missing=not bool(args.no_download_if_missing),
        download_retries=int(args.download_retries),
        download_sleep_sec=float(args.download_sleep_sec),
        continue_on_error=bool(args.continue_on_error),
        dry_run=bool(args.dry_run),
        parallel_workers=max(1, int(args.parallel_workers)),
        require_gpu=bool(args.require_gpu),
        gpu_check_interval_sec=float(args.gpu_check_interval_sec),
        gpu_worker_map=_resolve_gpu_worker_map(args),
    )

    catalog_path = Path(args.catalog_path)
    if not catalog_path.exists():
        raise FileNotFoundError(f"Catalog not found: {catalog_path}")
    rows = json.loads(catalog_path.read_text())
    if not isinstance(rows, list):
        raise ValueError("Catalog must be a JSON list.")

    if args.dataset_keys:
        keep = set(args.dataset_keys)
        rows = [r for r in rows if r.get("dataset_key") in keep]
    if args.max_datasets is not None:
        rows = rows[: int(args.max_datasets)]

    total = len(rows) * len(cfg.specs) * len(cfg.decoding_modes)
    progress_counter = [0]
    progress_lock = threading.Lock()
    stop_event = threading.Event()
    failures: list[dict[str, Any]] = []

    if cfg.parallel_workers == 1:
        worker_rows = [rows]
    else:
        worker_rows = [rows[i:: cfg.parallel_workers] for i in range(cfg.parallel_workers)]

    if cfg.gpu_worker_map is None:
        gpu_map = [None] * cfg.parallel_workers
    else:
        gpu_map = list(cfg.gpu_worker_map)

    if cfg.require_gpu and any(g is None for g in gpu_map):
        raise ValueError("When --require_gpu is enabled, provide --gpu_worker_map (e.g. 0,0,1,1).")

    print(
        f"[config] workers={cfg.parallel_workers} gpu_map={gpu_map} rows={len(rows)} total_jobs={total} require_gpu={cfg.require_gpu}",
        flush=True,
    )

    if cfg.parallel_workers == 1:
        failures.extend(
            _worker_loop(
                worker_idx=0,
                rows=worker_rows[0],
                cfg=cfg,
                gpu_id=gpu_map[0],
                stop_event=stop_event,
                progress_counter=progress_counter,
                progress_lock=progress_lock,
                total_jobs=total,
            )
        )
    else:
        with ThreadPoolExecutor(max_workers=cfg.parallel_workers) as ex:
            futs = []
            for i in range(cfg.parallel_workers):
                futs.append(
                    ex.submit(
                        _worker_loop,
                        i,
                        worker_rows[i],
                        cfg=cfg,
                        gpu_id=gpu_map[i],
                        stop_event=stop_event,
                        progress_counter=progress_counter,
                        progress_lock=progress_lock,
                        total_jobs=total,
                    )
                )
            for fut in as_completed(futs):
                try:
                    failures.extend(fut.result())
                except GpuUnavailableError:
                    stop_event.set()
                    # hard fail on GPU loss as requested
                    raise

    summary = {
        "catalog_path": str(catalog_path),
        "output_root": str(cfg.output_root),
        "rows_requested": len(rows),
        "specs": cfg.specs,
        "decoding_modes": cfg.decoding_modes,
        "alphas": cfg.alphas,
        "seed": cfg.seed,
        "jobs_total": total,
        "parallel_workers": cfg.parallel_workers,
        "gpu_worker_map": gpu_map,
        "require_gpu": cfg.require_gpu,
        "failures": failures,
    }
    (cfg.output_root / "summary.json").write_text(json.dumps(summary, indent=2))
    print(f"[done] wrote summary: {cfg.output_root / 'summary.json'}", flush=True)


if __name__ == "__main__":
    main()
